spring.application.name=aviation-routes-backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/aviation_routes
spring.datasource.username=postgres
spring.datasource.password=kavusxandar

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false